---
- name: Install diags agents and oms agents
  hosts: azure_vmachines
  vars_files: 
        - vmsvariables.yml
  become: true
  tasks:
        - name: Create VM Extension - diags
          azure_rm_virtualmachine_extension:
            name: "{{ inventory_hostname }}-diags"
            location: "{{ region }}"
            resource_group: "{{ resource_group}}"
            virtual_machine_name: "{{ inventory_hostname }}"
            publisher: "Microsoft.OSTCExtensions"
            virtual_machine_extension_type: "LinuxDiagnostic"
            type_handler_version: "{{ diags_type_handler_version }}"
            settings: "{{ diags_settings }}"
            auto_upgrade_minor_version: "true"
            client_id: "{{ client_id }}"
            secret: "{{ secret }}"
            subscription_id: "{{ subscription_id }}"
            tenant: "{{ tenant }}"

        - name: Create VM Extension - oms agent
          azure_rm_virtualmachine_extension:
            name: "{{ inventory_hostname }}-diags"
            location: "{{ region }}"
            resource_group: "{{ resource_group}}"
            virtual_machine_name: "{{ inventory_hostname }}"
            publisher: "Microsoft.EnterpriseCloud.Monitoring"
            virtual_machine_extension_type: "OmsAgentForLinux"
            type_handler_version: "{{ oms_type_handler_version }}"
            settings: "{{ omsagent_settings }}"
            protected_settings: "{{ omsagent_protected_settings  }}"
            auto_upgrade_minor_version: "{{ oms_agent_for_linux_vm_extn_auto_upgrade_minor_version }}"
            client_id: "{{ client_id }}"
            secret: "{{ secret }}"
            subscription_id: "{{ subscription_id }}"
            tenant: "{{ tenant }}"
